article --> [a].
article --> [an].
article --> [the].
variable_name --> [a].
variable_name --> [b].
variable_name --> [c].
variable_name --> [d].
variable_name --> [e].
variable_name --> [f].
variable_name --> [g].
variable_name --> [h].
variable_name --> [i].
variable_name --> [j].
variable_name --> [k].
variable_name --> [l].
variable_name --> [m].
variable_name --> [n].
variable_name --> [o].
variable_name --> [p].
variable_name --> [q].
variable_name --> [r].
variable_name --> [s].
variable_name --> [t].
variable_name --> [u].
variable_name --> [v].
variable_name --> [w].
variable_name --> [x].
variable_name --> [y].
variable_name --> [z].
number(X) --> [X], {integer(X), X >= 0}.
number(X) --> [X], {integer(X), X < 0}.
variable_specifier --> [variable].
variable_specifier --> [variables].
subtraction --> [-].
subtraction --> [minus].
division --> [divided,by].
division --> [/].
multiplication --> [multiplied,by].
multiplication --> [times].
multiplication --> [*].
addition --> [plus].
addition --> [+].
operator --> addition.
operator --> subtraction.
operator --> division.
operator --> multiplication.
linking_verb --> [is].
linking_verb --> [are].
gt --> [>].
gt --> linking_verb,[greater,than].
lt --> [<].
lt --> linking_verb,[less,than].
gte --> [>,=].
gte --> linking_verb,[greater,than,or,equal,to].
lte --> [<,=].
lte --> linking_verb,[less,than,or,equal,to].
equals --> [=].
equals --> [equals].
equals --> linking_verb,[equal,to].
equality --> gt.
equality --> gte.
equality --> lt.
equality --> lte.
equality --> equals.
reference_tag --> [it].
reference_tag --> [all,these].
reference_tag --> [all,the].
range(Start,End) --> [varies,from,Start,to,End].
range(Start,End) --> [lies,between,Start,and,End].
range(Start,End) --> linking_verb,[in,the,range,Start,to,End].
operand --> number(X).
operand --> variable_name.
expression --> operand.
expression --> operand,operator,operand.
expression --> operand,operator,expression.
expression --> article,[quotient,of],operand,[and],operand.
expression --> article,[product,of],operand,[and],operand.
sentence --> article,variable_specifier,variable_name,range(X,Y).
sentence --> variable_specifier,variable_name,range(X,Y).
sentence --> reference_tag,equality,expression.
sentence --> reference_tag,variable_specifier,equality,expression.
sentence --> variable_name,equality,expression.
sentence --> variable_specifier,variable_name,equality,expression.
